// Aktivite günlüğü tipleri (domain event isimleri — §47)
export const ActivityType = {
  // kurulum
  TENANT_SAVED: "TENANT_SAVED",
  EDITION_CREATED: "EDITION_CREATED",
  EDITION_SAVED: "EDITION_SAVED",
  EDITION_PUBLISHED: "EDITION_PUBLISHED",
  CAPABILITY_TOGGLED: "CAPABILITY_TOGGLED",
  CATEGORY_SAVED: "CATEGORY_SAVED",
  SCIENTIFIC_SAVED: "SCIENTIFIC_SAVED",
  // kimlik
  PERSON_SAVED: "PERSON_SAVED",
  PERSON_MERGED: "PERSON_MERGED",
  ORG_SAVED: "ORG_SAVED",
  ORG_ASSIGNMENT: "ORG_ASSIGNMENT",
  PARTICIPATION_SAVED: "PARTICIPATION_SAVED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  // kayıt & hak
  REGISTRATION_SAVED: "REGISTRATION_SAVED",
  REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
  REGISTRATION_CANCELLED: "REGISTRATION_CANCELLED",
  INVITATION_SENT: "INVITATION_SENT",
  ENTITLEMENT_SAVED: "ENTITLEMENT_SAVED",
  CLAIM_SAVED: "CLAIM_SAVED",
  // finans
  ORDER_SAVED: "ORDER_SAVED",
  PAYMENT_SAVED: "PAYMENT_SAVED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  REFUND_SAVED: "REFUND_SAVED",
  // sponsorluk
  SPONSOR_AGREEMENT: "SPONSOR_AGREEMENT",
  DELIVERABLE_SAVED: "DELIVERABLE_SAVED",
  BOOTH_ALLOCATED: "BOOTH_ALLOCATED",
  BOOTHS_SAVED: "BOOTHS_SAVED",
  // bilimsel & program
  SUBMISSION_SAVED: "SUBMISSION_SAVED",
  REVIEW_SAVED: "REVIEW_SAVED",
  DECISION_SAVED: "DECISION_SAVED",
  SESSION_SAVED: "SESSION_SAVED",
  PROGRAM_ASSIGNMENT: "PROGRAM_ASSIGNMENT",
  CME_SAVED: "CME_SAVED",
  // konaklama
  HOTEL_SAVED: "HOTEL_SAVED",
  RESERVATION_SAVED: "RESERVATION_SAVED",
  // saha & belge
  BADGE_SAVED: "BADGE_SAVED",
  SCAN_SAVED: "SCAN_SAVED",
  SCAN_ALLOWED: "SCAN_ALLOWED",
  SCAN_DENIED: "SCAN_DENIED",
  CERT_DEF_SAVED: "CERT_DEF_SAVED",
  CERT_ISSUE_SAVED: "CERT_ISSUE_SAVED",
  // iletişim & operasyon
  CAMPAIGN_SAVED: "CAMPAIGN_SAVED",
  TASK_SAVED: "TASK_SAVED",
} as const;

export type ActivityTypeValue = (typeof ActivityType)[keyof typeof ActivityType];
